services:
  - type: web
    name: fastcoach-frontend
    runtime: static
    rootDir: frontend
    buildCommand: "echo 'no build step needed'"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
