import React, {useEffect, useMemo, useState} from "react";
import {Activity, Award, BarChart3, CheckCircle2, ChevronRight, Clock3, Droplets, Flame, LayoutDashboard, LogOut, Menu, ShieldCheck, Sparkles, Trophy, Users, Wallet, X} from "lucide-react";
import {api} from "./api";

type User={_id?:string;id?:string;name:string;email:string;role:string;walletBalance?:number;referralCode?:string;stats?:any;challenge?:any;fasting?:any};
type Routine={fastingHours:number;eatingHours:number;meals:any[];tasks:any[]};

function App(){
  const [user,setUser]=useState<User|null>(null);
  const [view,setView]=useState("dashboard");
  const [mobile,setMobile]=useState(false);
  useEffect(()=>{const saved=localStorage.getItem("fc_user"); if(saved) setUser(JSON.parse(saved));},[]);
  if(!user) return <Auth onLogin={(u)=>{setUser(u);localStorage.setItem("fc_user",JSON.stringify(u))}}/>;
  const logout=()=>{localStorage.clear();setUser(null)};
  return <div className="min-h-screen bg-[#f7f8f6] text-slate-900">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur">
      <div className="mx-auto flex max-w-[1500px] items-center justify-between px-4 py-3 lg:px-7">
        <div className="flex items-center gap-3"><button className="rounded-xl p-2 lg:hidden" onClick={()=>setMobile(true)}><Menu size={22}/></button><Brand/></div>
        <div className="flex items-center gap-3"><div className="hidden text-right sm:block"><div className="text-sm font-semibold">{user.name}</div><div className="text-xs text-slate-500">{user.role==="admin"?"Coach":"Challenge Member"}</div></div><div className="grid h-10 w-10 place-items-center rounded-full bg-emerald-100 font-bold text-emerald-800">{user.name[0]}</div></div>
      </div>
    </header>
    <div className="mx-auto flex max-w-[1500px]">
      <aside className="hidden min-h-[calc(100vh-65px)] w-64 shrink-0 border-r border-slate-200 bg-white p-4 lg:block"><Nav role={user.role} view={view} setView={setView}/><button onClick={logout} className="mt-8 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-500 hover:bg-slate-50"><LogOut size={18}/> Sign out</button></aside>
      {mobile&&<div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-slate-950/30" onClick={()=>setMobile(false)}/><aside className="relative h-full w-72 bg-white p-5"><div className="mb-7 flex justify-between"><Brand/><button onClick={()=>setMobile(false)}><X/></button></div><Nav role={user.role} view={view} setView={(v)=>{setView(v);setMobile(false)}}/></aside></div>}
      <main className="min-w-0 flex-1 p-4 lg:p-7">{user.role==="admin"?<Admin view={view}/>:<Client user={user} view={view} setView={setView}/>}</main>
    </div>
  </div>
}

function Brand(){return <div className="flex items-center gap-2"><div className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-700 text-white shadow-soft"><Sparkles size={18}/></div><div><div className="text-sm font-extrabold tracking-tight">FASTING<span className="text-emerald-700">COACH</span></div><div className="text-[9px] font-semibold tracking-[.22em] text-slate-400">55 DAY SYSTEM</div></div></div>}

function Nav({role,view,setView}:{role:string;view:string;setView:(v:string)=>void}){const items=role==="admin"?[
  ["dashboard","Command Center",LayoutDashboard],["clients","Client Directory",Users],["payments","Payment Approvals",ShieldCheck],["leaderboard","Leaderboard",Trophy],["payouts","Referral Payouts",Wallet]
]:[
  ["dashboard","My Dashboard",LayoutDashboard],["routine","Daily Routine",CheckCircle2],["leaderboard","Leaderboard",Trophy],["referral","Refer & Earn",Wallet],["history","Progress History",BarChart3]
];return <nav className="space-y-1">{items.map(([id,label,I]:any)=><button key={id} onClick={()=>setView(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${view===id?"bg-emerald-50 text-emerald-800":"text-slate-600 hover:bg-slate-50"}`}><I size={18}/>{label}</button>)}</nav>}

function Auth({onLogin}:{onLogin:(u:User)=>void}){const [mode,setMode]=useState<"login"|"register">("login");const [form,setForm]=useState({name:"",email:"",password:"",referralCode:""});const [err,setErr]=useState("");const submit=async(e:any)=>{e.preventDefault();try{const data=await api(`/auth/${mode==="login"?"login":"register"}`,{method:"POST",body:JSON.stringify(form)});onLogin(data.user)}catch(e:any){setErr(e.message)}};return <div className="grid min-h-screen lg:grid-cols-2"><div className="hidden bg-emerald-950 p-12 text-white lg:flex lg:flex-col lg:justify-between"><Brand/><div className="max-w-xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-emerald-700 px-3 py-1 text-xs text-emerald-200"><Sparkles size={13}/> Coach-led accountability</div><h1 className="text-5xl font-extrabold leading-tight">A smarter structure for your 55-day transformation.</h1><p className="mt-5 max-w-lg text-emerald-100/75">Personalized routines, live fasting windows, streaks and human coaching — organized in one focused workspace.</p><div className="mt-10 grid grid-cols-3 gap-3">{["55 days","Live fasting","Peer accountability"].map(x=><div className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm">{x}</div>)}</div></div><div className="text-xs text-emerald-200/50">Designed for structured coaching programs.</div></div><div className="flex items-center justify-center p-5 sm:p-10"><form onSubmit={submit} className="w-full max-w-md"><Brand/><h2 className="mt-10 text-3xl font-extrabold">{mode==="login"?"Welcome back":"Start your challenge"}</h2><p className="mt-2 text-sm text-slate-500">{mode==="login"?"Sign in to continue your routine.":"Create your account. Activation follows payment approval."}</p>{mode==="register"&&<Field label="Full name" value={form.name} onChange={v=>setForm({...form,name:v})}/>}<Field label="Email" type="email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Field label="Password" type="password" value={form.password} onChange={v=>setForm({...form,password:v})}/>{mode==="register"&&<Field label="Referral code (optional)" value={form.referralCode} onChange={v=>setForm({...form,referralCode:v})}/>} {err&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{err}</div>}<button className="mt-6 w-full rounded-xl bg-emerald-700 py-3 font-semibold text-white hover:bg-emerald-800">{mode==="login"?"Sign in":"Create account"}</button><button type="button" onClick={()=>setMode(mode==="login"?"register":"login")} className="mt-4 w-full text-sm font-semibold text-emerald-700">{mode==="login"?"New here? Create an account":"Already registered? Sign in"}</button><p className="mt-8 text-center text-[11px] leading-5 text-slate-400">This app supports coaching workflows and does not replace individualized medical advice.</p></form></div></div>}

function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="mt-4 block text-sm font-medium text-slate-700">{label}<input required={label!=="Referral code (optional)"} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 outline-none ring-emerald-500 focus:ring-2"/></label>}

function Stat({icon:I,label,value,sub}:{icon:any;label:string;value:any;sub?:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><div className="flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><I size={19}/></div>{sub&&<span className="text-xs font-semibold text-emerald-700">{sub}</span>}</div><div className="mt-5 text-2xl font-extrabold tracking-tight">{value}</div><div className="mt-1 text-sm text-slate-500">{label}</div></div>}

function Client({user,view,setView}:{user:User;view:string;setView:(v:string)=>void}){const [data,setData]=useState<any>(null);const [leader,setLeader]=useState<any[]>([]);const [water,setWater]=useState(0);const [checked,setChecked]=useState<number[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([api("/me"),api("/leaderboard")]).then(([m,l])=>{setData(m);setLeader(l);setWater(m.log?.waterMl||0);setChecked(m.log?.completedTaskIndexes||[])}).finally(()=>setLoading(false))},[]);
 if(loading)return <Loader/>; const u=data.user; const routine=data.routine||{meals:[],tasks:[],fastingHours:16,eatingHours:8}; const day=u.challenge?.day||0; const adherence=u.stats?.adherence||0;
 const save=async(nextChecked=checked,nextWater=water)=>{await api("/daily-log",{method:"POST",body:JSON.stringify({waterMl:nextWater,completedTaskIndexes:nextChecked})});setData({...data,log:{...data.log,waterMl:nextWater,completedTaskIndexes:nextChecked}})};
 if(view==="routine")return <Routine routine={routine} checked={checked} setChecked={setChecked} water={water} setWater={setWater} save={save}/>;
 if(view==="leaderboard")return <Leaderboard data={leader}/>;
 if(view==="referral")return <Referral user={u}/>;
 if(view==="history")return <History/>;
 return <><PageTitle eyebrow={`DAY ${day} OF 55`} title={`Good day, ${u.name.split(" ")[0]}.`} desc="Your plan is ready. Stay consistent, complete the essentials and let the streak compound." action={<button onClick={()=>setView("routine")} className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white">Open today's routine <ChevronRight className="ml-1 inline" size={16}/></button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Flame} label="Current streak" value={`${u.stats?.streak||0} days`} sub="Keep going"/><Stat icon={Trophy} label="Challenge points" value={u.stats?.points||0}/><Stat icon={Droplets} label="Water today" value={`${water} ml`}/><Stat icon={Activity} label="Adherence" value={`${adherence}%`}/></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><FastingCard user={u}/><TodayCard routine={routine} checked={checked} onOpen={()=>setView("routine")}/></div></>}

function PageTitle({eyebrow,title,desc,action}:{eyebrow?:string;title:string;desc:string;action?:any}){return <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="text-xs font-bold tracking-[.16em] text-emerald-700">{eyebrow}</div><h1 className="mt-2 text-3xl font-extrabold tracking-tight sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{desc}</p></div>{action}</div>}

function FastingCard({user}:{user:User}){return <div className="rounded-2xl bg-emerald-950 p-6 text-white shadow-soft"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold text-emerald-200">LIVE FASTING WINDOW</div><div className="mt-1 text-2xl font-extrabold">{user.fasting?.status==="eating"?"Eating window":"Fasting"}</div></div><div className="rounded-xl bg-white/10 p-3"><Clock3/></div></div><div className="mt-8 flex items-center gap-8"><div className="grid h-36 w-36 place-items-center rounded-full border-[10px] border-emerald-700/70"><div className="text-center"><div className="text-3xl font-extrabold">16:00</div><div className="text-xs text-emerald-200">remaining</div></div></div><div className="max-w-sm text-sm text-emerald-100/75"><p>Follow the coach-assigned timing shown in your routine. Your app state is based on the schedule saved by your coach.</p><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/5 p-3"><div className="text-xs text-emerald-200">Fast</div><b>16 hours</b></div><div className="rounded-xl bg-white/5 p-3"><div className="text-xs text-emerald-200">Eat</div><b>8 hours</b></div></div></div></div></div>}

function TodayCard({routine,checked,onOpen}:{routine:Routine;checked:number[];onOpen:()=>void}){const done=checked.length,total=routine.tasks?.length||0;return <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><div className="flex items-center justify-between"><div><div className="text-xs font-bold tracking-[.14em] text-slate-400">TODAY</div><h3 className="mt-1 text-xl font-bold">Execution score</h3></div><div className="text-2xl font-extrabold text-emerald-700">{total?Math.round(done/total*100):0}%</div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{width:`${total?done/total*100:0}%`}}/></div><div className="mt-5 space-y-3">{(routine.tasks||[]).slice(0,3).map((t:any,i:number)=><div className="flex items-center gap-3 text-sm"><CheckCircle2 size={17} className={checked.includes(i)?"text-emerald-600":"text-slate-300"}/><span>{t.title}</span></div>)}</div><button onClick={onOpen} className="mt-6 w-full rounded-xl border border-slate-200 py-2.5 text-sm font-semibold hover:bg-slate-50">View full checklist</button></div>}

function Routine({routine,checked,setChecked,water,setWater,save}:{routine:Routine;checked:number[];setChecked:any;water:number;setWater:any;save:any}){return <><PageTitle eyebrow="DAILY EXECUTION" title="Today's routine" desc="Your coach-assigned plan, organized into a simple sequence. Complete what is assigned to you."/><div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><div className="flex items-center justify-between"><h3 className="text-xl font-bold">Daily checklist</h3><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{checked.length}/{routine.tasks?.length||0} complete</span></div><div className="mt-5 space-y-2">{(routine.tasks||[]).map((t:any,i:number)=><button key={i} onClick={()=>{const next=checked.includes(i)?checked.filter(x=>x!==i):[...checked,i];setChecked(next);save(next,water)}} className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left ${checked.includes(i)?"border-emerald-200 bg-emerald-50":"border-slate-100 hover:bg-slate-50"}`}><div className={`grid h-7 w-7 place-items-center rounded-full border ${checked.includes(i)?"border-emerald-600 bg-emerald-600 text-white":"border-slate-300"}`}>{checked.includes(i)&&<CheckCircle2 size={16}/>}</div><div className="flex-1"><div className="font-semibold">{t.title}</div><div className="mt-0.5 text-xs text-slate-500">{t.category} · +{t.points||5} points</div></div></button>)}</div></div><div className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><div className="flex items-center gap-3"><Droplets className="text-sky-600"/><h3 className="font-bold">Hydration</h3></div><div className="mt-5 text-3xl font-extrabold">{water}<span className="text-base font-medium text-slate-400"> ml</span></div><p className="mt-1 text-sm text-slate-500">Log water in 250 ml increments.</p><button onClick={()=>{const n=water+250;setWater(n);save(checked,n)}} className="mt-5 w-full rounded-xl bg-slate-900 py-2.5 text-sm font-semibold text-white">+250 ml</button></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><h3 className="font-bold">Assigned meals</h3><div className="mt-4 space-y-3">{(routine.meals||[]).map((m:any,i:number)=><div key={i} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between"><b className="text-sm">{m.name}</b><span className="text-xs text-slate-400">{m.time}</span></div><div className="mt-1 text-xs text-slate-500">{m.calories||"—"} kcal · P {m.protein||"—"}g · C {m.carbs||"—"}g · F {m.fat||"—"}g</div></div>)}</div></div></div></div></>}

function Leaderboard({data}:{data:any[]}){return <><PageTitle eyebrow="COHORT PERFORMANCE" title="Leaderboard" desc="A transparent view of consistency across active challenge members."/><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><tr><th className="p-3">Rank</th><th className="p-3">Member</th><th className="p-3">Day</th><th className="p-3">Points</th><th className="p-3">Adherence</th></tr></thead><tbody>{data.map((x,i)=><tr className="border-b border-slate-50"><td className="p-3 font-bold">{i+1}</td><td className="p-3 font-semibold">{x.name}</td><td className="p-3">{x.challenge?.day||0}/55</td><td className="p-3">{x.stats?.points||0}</td><td className="p-3">{x.stats?.adherence||0}%</td></tr>)}</tbody></table></div></div></>}

function Referral({user}: {user:any}){const [amount,setAmount]=useState(500);const [msg,setMsg]=useState("");return <><PageTitle eyebrow="REFERRAL LOOP" title="Refer & earn" desc="Share your unique code. Successful approved paid activations add ₹500 to your wallet."/><div className="grid gap-5 lg:grid-cols-3"><div className="rounded-2xl bg-emerald-950 p-6 text-white lg:col-span-2"><div className="text-sm text-emerald-200">YOUR INVITE CODE</div><div className="mt-3 text-4xl font-extrabold tracking-wider">{user.referralCode||"—"}</div><button onClick={()=>navigator.clipboard?.writeText(user.referralCode||"")} className="mt-5 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-emerald-900">Copy code</button></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><div className="text-sm text-slate-500">Available wallet</div><div className="mt-2 text-3xl font-extrabold">₹{user.walletBalance||0}</div><input type="number" min={500} value={amount} onChange={e=>setAmount(+e.target.value)} className="mt-5 w-full rounded-xl border p-3"/><button onClick={async()=>{try{await api("/payouts",{method:"POST",body:JSON.stringify({amount,upiId:""})});setMsg("Payout request submitted.")}catch(e:any){setMsg(e.message)}}} className="mt-3 w-full rounded-xl bg-emerald-700 py-2.5 text-sm font-semibold text-white">Request payout</button>{msg&&<p className="mt-3 text-xs text-slate-500">{msg}</p>}</div></div></>}

function History(){return <><PageTitle eyebrow="PROGRESS" title="History & trends" desc="Use this space for weight, adherence and streak history as your coaching program grows."/><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><h3 className="font-bold">Weight trend</h3><div className="mt-8 flex h-56 items-end gap-3">{[65,70,63,76,72,82,78,88].map((h,i)=><div className="flex-1 rounded-t-lg bg-emerald-100" style={{height:`${h}%`}}><div className="h-full w-full rounded-t-lg bg-emerald-600 opacity-70"/></div>)}</div><div className="mt-4 flex justify-between text-xs text-slate-400"><span>Start</span><span>Current</span></div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><h3 className="font-bold">Consistency</h3><div className="mt-6 space-y-4">{["Checklist completion","Hydration logging","Routine adherence"].map((x,i)=><div><div className="mb-2 flex justify-between text-sm"><span>{x}</span><b>{[84,76,91][i]}%</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-600" style={{width:`${[84,76,91][i]}%`}}/></div></div>)}</div></div></div></>}

function Admin({view}:{view:string}){const [clients,setClients]=useState<any[]>([]);const [payments,setPayments]=useState<any[]>([]);const [leader,setLeader]=useState<any[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{Promise.all([api("/admin/clients"),api("/admin/payments"),api("/leaderboard")]).then(([c,p,l])=>{setClients(c);setPayments(p);setLeader(l)}).finally(()=>setLoading(false))},[]);if(loading)return <Loader/>;if(view==="clients")return <AdminClients clients={clients}/>;if(view==="payments")return <Payments payments={payments} refresh={()=>api("/admin/payments").then(setPayments)}/>;if(view==="leaderboard")return <Leaderboard data={leader}/>;if(view==="payouts")return <AdminPayouts/>;return <><PageTitle eyebrow="COACH OPERATIONS" title="Command center" desc="Monitor the cohort, review activation queues and keep individualized routines moving."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Users} label="Active clients" value={clients.filter(x=>x.challenge?.active).length}/><Stat icon={ShieldCheck} label="Pending payments" value={payments.filter(x=>x.status==="pending").length}/><Stat icon={Flame} label="Avg. adherence" value={`${clients.length?Math.round(clients.reduce((a,x)=>a+(x.stats?.adherence||0),0)/clients.length):0}%`}/><Stat icon={Wallet} label="Wallet activity" value="₹500/referral"/></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><div className="flex justify-between"><h3 className="font-bold">Client pulse</h3><span className="text-xs text-slate-400">Live roster snapshot</span></div><div className="mt-5 space-y-3">{clients.slice(0,6).map(x=><div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-emerald-100 text-sm font-bold text-emerald-800">{x.name[0]}</div><div className="flex-1"><div className="text-sm font-semibold">{x.name}</div><div className="text-xs text-slate-500">Day {x.challenge?.day||0}/55 · {x.fasting?.status||"inactive"}</div></div><b className="text-sm">{x.stats?.adherence||0}%</b></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><h3 className="font-bold">Activation queue</h3><div className="mt-5 space-y-3">{payments.filter(x=>x.status==="pending").slice(0,5).map(p=><div className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><ShieldCheck className="text-amber-600"/><div className="flex-1"><div className="text-sm font-semibold">{p.userId?.name}</div><div className="text-xs text-slate-500">{p.tier} · ₹{p.amount} · UTR {p.utr}</div></div><button className="text-xs font-semibold text-emerald-700" onClick={async()=>{await api(`/admin/payments/${p._id}`,{method:"PATCH",body:JSON.stringify({status:"approved"})});location.reload()}}>Approve</button></div>)}</div></div></div></>}

function AdminClients({clients}:{clients:any[]}){const [selected,setSelected]=useState<any>(null);return <><PageTitle eyebrow="CLIENT DIRECTORY" title="Client monitoring" desc="Review challenge day, adherence, fasting state and open a client profile for routine management."/><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-soft"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-slate-400"><tr><th className="p-4">Client</th><th className="p-4">Challenge</th><th className="p-4">Adherence</th><th className="p-4">Fasting</th><th className="p-4">Points</th><th/></tr></thead><tbody>{clients.map(c=><tr className="border-b border-slate-50"><td className="p-4 font-semibold">{c.name}<div className="text-xs font-normal text-slate-400">{c.email}</div></td><td className="p-4">Day {c.challenge?.day||0}/55</td><td className="p-4">{c.stats?.adherence||0}%</td><td className="p-4 capitalize">{c.fasting?.status||"inactive"}</td><td className="p-4">{c.stats?.points||0}</td><td className="p-4"><button onClick={()=>setSelected(c)} className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-semibold">Manage</button></td></tr>)}</tbody></table></div>{selected&&<RoutineEditor client={selected} close={()=>setSelected(null)}/>}</>}

function RoutineEditor({client,close}:{client:any;close:()=>void}){const [hours,setHours]=useState(16);const [tasks,setTasks]=useState([{title:"Morning starter",category:"Nutrition",points:10},{title:"Protein target",category:"Nutrition",points:15},{title:"Workout / movement",category:"Activity",points:15}]);const save=async()=>{const now=new Date();const fastEnd=new Date(now.getTime()+hours*3600000);const eatEnd=new Date(fastEnd.getTime()+(24-hours)*3600000);await api(`/admin/clients/${client._id}/routine`,{method:"PUT",body:JSON.stringify({fastStart:now.toISOString(),fastEnd:fastEnd.toISOString(),eatingStart:fastEnd.toISOString(),eatingEnd:eatEnd.toISOString(),fastingHours:hours,eatingHours:24-hours,meals:[],tasks})});close()};return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><div className="text-xs font-bold tracking-widest text-emerald-700">ROUTINE BUILDER</div><h2 className="mt-1 text-2xl font-extrabold">{client.name}</h2></div><button onClick={close}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Fasting hours<input type="number" value={hours} onChange={e=>setHours(+e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label><div className="rounded-xl bg-slate-50 p-3 text-sm"><b>Eating hours</b><div className="mt-1 text-slate-500">{24-hours} hours</div></div></div><h3 className="mt-7 font-bold">Habit checklist</h3><div className="mt-3 space-y-2">{tasks.map((t,i)=><input key={i} value={t.title} onChange={e=>setTasks(tasks.map((x,j)=>j===i?{...x,title:e.target.value}:x))} className="w-full rounded-xl border p-3 text-sm"/>)}</div><div className="mt-7 flex justify-end gap-3"><button onClick={close} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button onClick={save} className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white">Save routine</button></div></div></div>}

function Payments({payments,refresh}:{payments:any[];refresh:()=>void}){return <><PageTitle eyebrow="PAYMENT OPERATIONS" title="Payment approvals" desc="Review manually submitted UPI proof and UTR details before activating a 55-day challenge."/><div className="space-y-3">{payments.map(p=><div className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-soft md:flex-row md:items-center"><div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><ShieldCheck/></div><div className="flex-1"><div className="font-bold">{p.userId?.name} · {p.tier}</div><div className="mt-1 text-xs text-slate-500">₹{p.amount} · UTR {p.utr} · {new Date(p.submittedAt).toLocaleString()}</div></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${p.status==="pending"?"bg-amber-50 text-amber-700":p.status==="approved"?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{p.status}</span>{p.status==="pending"&&<div className="flex gap-2"><button onClick={async()=>{await api(`/admin/payments/${p._id}`,{method:"PATCH",body:JSON.stringify({status:"approved"})});refresh()}} className="rounded-xl bg-emerald-700 px-3 py-2 text-xs font-semibold text-white">Approve</button><button onClick={async()=>{await api(`/admin/payments/${p._id}`,{method:"PATCH",body:JSON.stringify({status:"rejected"})});refresh()}} className="rounded-xl border px-3 py-2 text-xs font-semibold">Reject</button></div>}</div>)}</div></>}

function AdminPayouts(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{api("/admin/payouts").then(setItems)},[]);return <><PageTitle eyebrow="REFERRAL OPERATIONS" title="Payout requests" desc="Review wallet withdrawal requests and mark them paid after external UPI settlement."/><div className="space-y-3">{items.map(p=><div className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><Wallet className="text-emerald-700"/><div className="flex-1"><b>{p.userId?.name}</b><div className="text-xs text-slate-500">₹{p.amount} · {p.upiId||"UPI not supplied"}</div></div><span className="text-xs font-semibold">{p.status}</span>{p.status==="pending"&&<button onClick={async()=>{await api(`/admin/payouts/${p._id}`,{method:"PATCH",body:JSON.stringify({status:"paid"})});location.reload()}} className="rounded-xl bg-emerald-700 px-3 py-2 text-xs font-semibold text-white">Mark paid</button>}</div>)}</div></>}

function Loader(){return <div className="grid min-h-[50vh] place-items-center"><div className="text-center"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-slate-200 border-t-emerald-700"/><p className="mt-3 text-sm text-slate-500">Loading workspace…</p></div></div>}
